module.exports = {
  apps: [
    {
      name: "mrt-api",
      script: "dist/server.js",
      cwd: "./backend",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "./logs/api-error.log",
      out_file: "./logs/api-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      max_memory_restart: "512M",
    },
    {
      name: "mrt-worker-matching",
      script: "dist/worker.js",
      cwd: "./backend",
      instances: 1,
      exec_mode: "fork",
      args: ["matching"],
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/worker-matching-error.log",
      out_file: "./logs/worker-matching-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      max_memory_restart: "256M",
    },
    {
      name: "mrt-worker-notification",
      script: "dist/worker.js",
      cwd: "./backend",
      instances: 1,
      exec_mode: "fork",
      args: ["notification"],
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/worker-notification-error.log",
      out_file: "./logs/worker-notification-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      max_memory_restart: "256M",
    },
    {
      name: "mrt-worker-purge",
      script: "dist/worker.js",
      cwd: "./backend",
      instances: 1,
      exec_mode: "fork",
      args: ["purge"],
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/worker-purge-error.log",
      out_file: "./logs/worker-purge-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      max_memory_restart: "256M",
    },
    {
      name: "mrt-worker-expiration",
      script: "dist/worker.js",
      cwd: "./backend",
      instances: 1,
      exec_mode: "fork",
      args: ["expiration"],
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/worker-expiration-error.log",
      out_file: "./logs/worker-expiration-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      max_memory_restart: "256M",
    },
  ],
};
